name: Deploy to shinyapps.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      # 👇 System libraries needed for R packages compiled from source
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            libcurl4-openssl-dev \
            libssl-dev \
            libxml2-dev \
            libgit2-dev \
            pkg-config

          # spatial stack likely needed by sf/terra
          sudo apt-get install -y --no-install-recommends \
            libgdal-dev \
            libgeos-dev \
            libproj-dev \
            libudunits2-dev \
            libsqlite3-dev

      # renv restore (now that sysdeps exist)
      - name: Restore renv
        uses: r-lib/actions/setup-renv@v2

      - name: Ensure rsconnect
        run: Rscript -e 'install.packages("rsconnect", repos="https://cloud.r-project.org")'

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}
        run: |
          Rscript -e 'rsconnect::setAccountInfo(name=Sys.getenv("SHINYAPPS_ACCOUNT"), token=Sys.getenv("SHINYAPPS_TOKEN"), secret=Sys.getenv("SHINYAPPS_SECRET"))'
          Rscript -e 'rsconnect::deployApp(appName = Sys.getenv("SHINYAPPS_APPNAME"), forceUpdate = TRUE, launch.browser = FALSE)'
