name: Deploy to shinyapps.io

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
      SHINYAPPS_TOKEN:   ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET:  ${{ secrets.SHINYAPPS_SECRET }}
      SHINYAPPS_APPNAME: ${{ secrets.SHINYAPPS_APPNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2

      # Install dependencies from DESCRIPTION using pak
      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rsconnect
          needs: project

      # Debug that secrets are actually present (lengths are safe to print)
      - name: Debug env
        run: |
          echo "ACCOUNT length: ${#SHINYAPPS_ACCOUNT}"
          echo "APPNAME: ${SHINYAPPS_APPNAME}"

      - name: Fail fast if secrets missing
        run: |
          test -n "$SHINYAPPS_ACCOUNT" || { echo "SHINYAPPS_ACCOUNT is empty"; exit 1; }
          test -n "$SHINYAPPS_TOKEN"   || { echo "SHINYAPPS_TOKEN is empty"; exit 1; }
          test -n "$SHINYAPPS_SECRET"  || { echo "SHINYAPPS_SECRET is empty"; exit 1; }
          test -n "$SHINYAPPS_APPNAME" || { echo "SHINYAPPS_APPNAME is empty"; exit 1; }

      - name: Deploy to shinyapps.io
        run: |
          Rscript -e 'rsconnect::setAccountInfo(
                        name   = Sys.getenv("SHINYAPPS_ACCOUNT"),
                        token  = Sys.getenv("SHINYAPPS_TOKEN"),
                        secret = Sys.getenv("SHINYAPPS_SECRET")
                      )'
          Rscript -e 'rsconnect::deployApp(
                        appName        = Sys.getenv("SHINYAPPS_APPNAME"),
                        forceUpdate    = TRUE,
                        launch.browser = FALSE
                      )'
